#!/usr/bin/bash

# Extractor de información de nmap

function extractPorts(){
	ports="$(cat $1 | grep -oP '\d{1,5}/open' | awk '{print $1}' FS='/' | xargs | tr ' ' ',')"
	ip_address="$(cat $1 | grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | sort -u | head -n 1)"
	echo -e "\n[*] Extrayendo información...\n" > extractPorts.tmp
	echo -e "\t[*] Dirección IP: $ip_address"  >> extractPorts.tmp
	echo -e "\t[*] Puertos abiertos: $ports\n"  >> extractPorts.tmp
	echo $ports | tr -d '\n' | xclip -sel clip
	echo -e "[*] Puertos copiados al portapapel\n"  >> extractPorts.tmp
	cat extractPorts.tmp; rm extractPorts.tmp
}
